### PR TITLE
Upgrade to latest Material, D3 Chart, and perfect lighthouse score

### PR DESCRIPTION
**Pull request by headwinds**
This update includes:

- latest material ui for react
- D3 Chart with useSelector to show how redux works with hooks
- accessibility testing with react-axe
- it now has 100% lighthouse for every category

### CODE REVIEW

**Comment by headwinds** [comment]
@ooade did you get a chance to look at this?

[demo](https://nextss-headwinds.now.sh/)

Screen Shot 2019-08-06 at 5 22 01 PM

**Comment by ooade** [comment]
It's not responsive on mobile. I was going to fix that myself but I've been caught up with a lot of things.
Screenshot_20190807-052426

**Comment by headwinds** [comment]
Ahhhh I didn’t check mobile - I didn’t realize the original was responsive - my bad - hang on I’ll make it responsive today and update the PR

**Comment by ooade** [comment]
Oh, Cool one then @headwinds 💃

**Comment by ooade** [comment]
Great work @headwinds!!!! I would love to make some changes tho, can you point to a different branch here?

**Comment by headwinds** [comment]
closing this master branch as I've create a separate PR for a feature branch

**Comment by ooade** [comment]
Thanks a lot!

**Pull request closed without merging**
