### PR TITLE
upgrade react and next

### PR DESCRIPTION
**Pull request by ogunsolahabib**
Upgraded Next.js to 13 and React to 18

### CODE REVIEW

**Comment by ooade** [comment]
Service workers seem broken.

**Comment by ogunsolahabib** [comment]
> Service workers seem broken.

[Next-offline](https://www.npmjs.com/package/next-offline) has not been updated in over 2 years. And Newer versions of Next don't seem to accept workboxOpts in next.config.js.

So I'll have to either leave next 12 or switch to [next-pwa](https://www.npmjs.com/package/next-pwa)

**Comment by ooade** [comment]
> > Service workers seem broken.
> 
> [Next-offline](https://www.npmjs.com/package/next-offline) has not been updated in over 2 years. And Newer versions of Next don't seem to accept workboxOpts in next.config.js.
> 
> So I'll have to either leave next 12 or switch to [next-pwa](https://www.npmjs.com/package/next-pwa)

It's probably going to be the same with next-pwa.

**Comment by ooade** [comment]
Can you help resolve the conflicts? 🤲🏾

**Comment by ooade** [comment]
Is this PR still relevant? Since the packages got updated in the last one?

**Comment by ogunsolahabib** [comment]
No, it's not needed anymore. I can close it.

**Pull request closed without merging**
